"""init after update

Revision ID: 56322c69e67d
Revises: 0db8fcebc879
Create Date: 2023-08-23 09:06:22.535937

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '56322c69e67d'
down_revision: Union[str, None] = '0db8fcebc879'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'panel_admin_hash',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('panel_admin_id', sa.Integer(), nullable=False),
        sa.Column('hash', sa.String(length=128), nullable=True),
        sa.Column('rand_string', sa.String(length=128), nullable=True),
        sa.Column('ip', sa.Integer(), nullable=True),
        sa.Column('remember', sa.Integer(), nullable=True),
        sa.Column('super_user', sa.Integer(), nullable=True),
        sa.Column('created_at', sa.Integer(), nullable=True),
        sa.Column('updated_at', sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint('id'),
        schema='panels',
        mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_panels_panel_admin_hash_hash'), 'panel_admin_hash', ['hash'], unique=False,
                    schema='panels')
    op.create_index(op.f('ix_panels_panel_admin_hash_panel_admin_id'), 'panel_admin_hash', ['panel_admin_id'],
                    unique=False, schema='panels')
    op.create_table(
        'panel_user_custom_fields',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('variable_name', sa.String(length=100), nullable=True),
        sa.Column('translation_code', sa.String(length=50), nullable=True),
        sa.Column('rules', sa.JSON(), nullable=True),
        sa.Column('position', sa.Integer(), nullable=True),
        sa.Column('default', sa.Integer(), nullable=True),
        sa.Column('created_at', sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint('id'),
        schema='panels',
        mysql_engine='InnoDB'
    )
    op.create_table(
        'panels',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('domain', sa.String(length=1000), nullable=True),
        sa.Column('created_at', sa.Integer(), nullable=True),
        sa.Column('expired_at', sa.Integer(), nullable=True),
        sa.Column('currency', sa.String(length=3), nullable=False),
        sa.Column('plan_id', sa.Integer(), nullable=False),
        sa.Column('db_name', sa.String(length=45), nullable=False),
        sa.Column('status', sa.Integer(), nullable=True, comment='1 - active, 2 - paused, 3 - deleted'),
        sa.PrimaryKeyConstraint('id'),
        schema='panels',
        mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_panels_panels_currency'), 'panels', ['currency'], unique=False, schema='panels')
    op.create_index(op.f('ix_panels_panels_plan_id'), 'panels', ['plan_id'], unique=False, schema='panels')
    op.create_table(
        'payment_methods',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(length=100), nullable=True),
        sa.Column('addfunds_form', sa.JSON(), nullable=True),
        sa.Column('settings_form', sa.JSON(), nullable=True),
        sa.Column('settings_form_description', sa.String(length=300), nullable=True),
        sa.Column('has_take_fee', sa.Integer(), nullable=True),
        sa.Column('has_extra_fee', sa.Integer(), nullable=True),
        sa.Column('created_at', sa.Integer(), nullable=True),
        sa.Column('updated_at', sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint('id'),
        schema='panels',
        mysql_engine='InnoDB'
    )
    op.create_table(
        'plan_list',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(length=45), nullable=True),
        sa.PrimaryKeyConstraint('id'),
        schema='panels',
        mysql_engine='InnoDB'
    )
    op.create_table(
        'user_agent_list',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('user_agent_name', sa.String(length=300), nullable=True),
        sa.PrimaryKeyConstraint('id'),
        schema='panels',
        mysql_engine='InnoDB'
    )
    op.create_table(
        'panel_admin',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('panel_id', sa.Integer(), nullable=True),
        sa.Column('panel_admin_hash_id', sa.Integer(), nullable=True),
        sa.Column('email', sa.String(length=300), nullable=True),
        sa.Column('password', sa.String(length=300), nullable=True),
        sa.Column('password_salt', sa.String(length=300), nullable=True),
        sa.Column('authorization_at', sa.Integer(), nullable=True),
        sa.Column('status', sa.Integer(), nullable=True, comment='1 - Active, 2 - Suspended'),
        sa.Column('created_at', sa.Integer(), nullable=True),
        sa.Column('updated_at', sa.Integer(), nullable=True),
        sa.Column('dark_mode', sa.Integer(), nullable=True, comment='0 - disabled, 1 - enabled'),
        sa.Column('rules', sa.JSON(), nullable=True),
        sa.ForeignKeyConstraint(['panel_admin_hash_id'], ['panels.panel_admin_hash.id'], onupdate='NO ACTION',
                                ondelete='NO ACTION'),
        sa.ForeignKeyConstraint(['panel_id'], ['panels.panels.id'], onupdate='NO ACTION', ondelete='NO ACTION'),
        sa.PrimaryKeyConstraint('id'),
        schema='panels',
        mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_panels_panel_admin_panel_id'), 'panel_admin', ['panel_id'], unique=False, schema='panels')
    op.create_table(
        'panel_domains',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('panel_id', sa.Integer(), nullable=True),
        sa.Column('domain', sa.String(length=300), nullable=True),
        sa.Column('domain_type', sa.Integer(), nullable=True,
                  comment='Тип домена: 1 - основной, 2 - системный, 3 - дополнительный'),
        sa.ForeignKeyConstraint(['panel_id'], ['panels.panels.id'], onupdate='NO ACTION', ondelete='NO ACTION'),
        sa.PrimaryKeyConstraint('id'),
        schema='panels',
        mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_panels_panel_domains_domain'), 'panel_domains', ['domain'], unique=False,
                    schema='panels')
    op.create_index(op.f('ix_panels_panel_domains_domain_type'), 'panel_domains', ['domain_type'], unique=True,
                    schema='panels')
    op.create_index(op.f('ix_panels_panel_domains_panel_id'), 'panel_domains', ['panel_id'], unique=False,
                    schema='panels')
    op.create_table(
        'panel_options',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('panel_id', sa.Integer(), nullable=True),
        sa.Column('signup_page', sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(['panel_id'], ['panels.panels.id'], onupdate='NO ACTION', ondelete='NO ACTION'),
        sa.PrimaryKeyConstraint('id'),
        schema='panels',
        mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_panels_panel_options_panel_id'), 'panel_options', ['panel_id'], unique=False,
                    schema='panels')
    op.create_table(
        'payment_methods_currencies',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('method_id', sa.Integer(), nullable=True),
        sa.Column('currency', sa.String(length=3), nullable=True),
        sa.Column('position', sa.Integer(), nullable=True),
        sa.Column('settings_form', sa.JSON(), nullable=True),
        sa.Column('settings_form_description', sa.String(length=300), nullable=True),
        sa.Column('is_available', sa.Integer(), nullable=True),
        sa.Column('created_at', sa.Integer(), nullable=True),
        sa.Column('updated_at', sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(['method_id'], ['panels.payment_methods.id'], onupdate='NO ACTION', ondelete='NO ACTION'),
        sa.PrimaryKeyConstraint('id'),
        schema='panels',
        mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_panels_payment_methods_currencies_currency'), 'payment_methods_currencies',
                    ['currency'], unique=True, schema='panels')
    op.create_index(op.f('ix_panels_payment_methods_currencies_method_id'), 'payment_methods_currencies',
                    ['method_id'], unique=True, schema='panels')
    op.create_table(
        'panel_payment_methods',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('panel_id', sa.Integer(), nullable=True),
        sa.Column('method_id', sa.Integer(), nullable=True),
        sa.Column('currency_id', sa.Integer(), nullable=True),
        sa.Column('is_visible', sa.Boolean(), nullable=True),
        sa.Column('webhook_url', sa.String(length=500), nullable=True),
        sa.Column('is_test_mode', sa.Boolean(), nullable=True),
        sa.Column('min_amount', sa.Integer(), nullable=True),
        sa.Column('max_amount', sa.Integer(), nullable=True),
        sa.Column('is_deleted', sa.Integer(), nullable=True),
        sa.Column('amount_currency', sa.Integer(), nullable=True),
        sa.Column('has_available_for_new_user', sa.Integer(), nullable=True),
        sa.Column('position', sa.Integer(), nullable=True),
        sa.Column('has_extra_fee', sa.Integer(), nullable=True),
        sa.Column('has_take_from_user', sa.Integer(), nullable=True),
        sa.Column('created_at', sa.Integer(), nullable=True),
        sa.Column('updated_at', sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(['currency_id'], ['panels.payment_methods_currencies.id'], onupdate='NO ACTION',
                                ondelete='NO ACTION'),
        sa.ForeignKeyConstraint(['method_id'], ['panels.payment_methods.id'], onupdate='NO ACTION',
                                ondelete='NO ACTION'),
        sa.ForeignKeyConstraint(['panel_id'], ['panels.panels.id'], onupdate='NO ACTION',
                                ondelete='NO ACTION'),
        sa.PrimaryKeyConstraint('id'),
        schema='panels',
        mysql_engine='InnoDB'
    )
    op.create_table(
        'panel_payment_methods_bonuses',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('panel_payment_methods_id', sa.Integer(), nullable=True),
        sa.Column('amount_percent', sa.Integer(), nullable=True),
        sa.Column('deposit_from', sa.Integer(), nullable=True),
        sa.Column('is_available', sa.Integer(), nullable=True),
        sa.Column('created_at', sa.Integer(), nullable=True),
        sa.Column('updated_at', sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(['panel_payment_methods_id'], ['panels.panel_payment_methods.id'],
                                onupdate='NO ACTION', ondelete='NO ACTION'),
        sa.PrimaryKeyConstraint('id'),
        schema='panels',
        mysql_engine='InnoDB'
    )
    op.create_table(
        'panel_payment_methods_options',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('panel_payment_methods_id', sa.Integer(), nullable=True),
        sa.Column('options', sa.Text(length=5000), nullable=True),
        sa.ForeignKeyConstraint(['panel_payment_methods_id'], ['panels.panel_payment_methods.id'],
                                onupdate='NO ACTION', ondelete='NO ACTION'),
        sa.PrimaryKeyConstraint('id'),
        schema='panels',
        mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('panel_payment_methods_options', schema='panels')
    op.drop_table('panel_payment_methods_bonuses', schema='panels')
    op.drop_table('panel_payment_methods', schema='panels')
    op.drop_index(op.f('ix_panels_payment_methods_currencies_method_id'), table_name='payment_methods_currencies',
                  schema='panels')
    op.drop_index(op.f('ix_panels_payment_methods_currencies_currency'), table_name='payment_methods_currencies',
                  schema='panels')
    op.drop_table('payment_methods_currencies', schema='panels')
    op.drop_index(op.f('ix_panels_panel_options_panel_id'), table_name='panel_options', schema='panels')
    op.drop_table('panel_options', schema='panels')
    op.drop_index(op.f('ix_panels_panel_domains_panel_id'), table_name='panel_domains', schema='panels')
    op.drop_index(op.f('ix_panels_panel_domains_domain_type'), table_name='panel_domains', schema='panels')
    op.drop_index(op.f('ix_panels_panel_domains_domain'), table_name='panel_domains', schema='panels')
    op.drop_table('panel_domains', schema='panels')
    op.drop_index(op.f('ix_panels_panel_admin_panel_id'), table_name='panel_admin', schema='panels')
    op.drop_table('panel_admin', schema='panels')
    op.drop_table('user_agent_list', schema='panels')
    op.drop_table('plan_list', schema='panels')
    op.drop_table('payment_methods', schema='panels')
    op.drop_index(op.f('ix_panels_panels_plan_id'), table_name='panels', schema='panels')
    op.drop_index(op.f('ix_panels_panels_currency'), table_name='panels', schema='panels')
    op.drop_table('panels', schema='panels')
    op.drop_table('panel_user_custom_fields', schema='panels')
    op.drop_index(op.f('ix_panels_panel_admin_hash_panel_admin_id'), table_name='panel_admin_hash', schema='panels')
    op.drop_index(op.f('ix_panels_panel_admin_hash_hash'), table_name='panel_admin_hash', schema='panels')
    op.drop_table('panel_admin_hash', schema='panels')
    # ### end Alembic commands ###
