"""panels_timezone

Revision ID: 20dc4e8ae15a
Revises: 56322c69e67d
Create Date: 2023-08-23 10:55:27.058795

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '20dc4e8ae15a'
down_revision: Union[str, None] = '56322c69e67d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('panel_admin', sa.Column('timezone', sa.Integer(), nullable=True))
    op.drop_constraint('panel_admin_ibfk_2', 'panel_admin', type_='foreignkey')
    op.drop_constraint('panel_admin_ibfk_1', 'panel_admin', type_='foreignkey')
    op.create_foreign_key(None, 'panel_admin', 'panel_admin_hash', ['panel_admin_hash_id'], ['id'], source_schema='panels', referent_schema='panels', onupdate='NO ACTION', ondelete='NO ACTION')
    op.create_foreign_key(None, 'panel_admin', 'panels', ['panel_id'], ['id'], source_schema='panels', referent_schema='panels', onupdate='NO ACTION', ondelete='NO ACTION')
    op.drop_index('ix_panels_panel_domains_domain', table_name='panel_domains')
    op.create_index(op.f('ix_panels_panel_domains_domain'), 'panel_domains', ['domain'], unique=True, schema='panels')
    op.drop_index('ix_panels_panel_domains_domain_type', table_name='panel_domains')
    op.create_index(op.f('ix_panels_panel_domains_domain_type'), 'panel_domains', ['domain_type'], unique=False, schema='panels')
    op.drop_constraint('panel_domains_ibfk_1', 'panel_domains', type_='foreignkey')
    op.create_foreign_key(None, 'panel_domains', 'panels', ['panel_id'], ['id'], source_schema='panels', referent_schema='panels', onupdate='NO ACTION', ondelete='NO ACTION')
    op.drop_constraint('panel_options_ibfk_1', 'panel_options', type_='foreignkey')
    op.create_foreign_key(None, 'panel_options', 'panels', ['panel_id'], ['id'], source_schema='panels', referent_schema='panels', onupdate='NO ACTION', ondelete='NO ACTION')
    op.drop_constraint('panel_payment_methods_ibfk_1', 'panel_payment_methods', type_='foreignkey')
    op.drop_constraint('panel_payment_methods_ibfk_3', 'panel_payment_methods', type_='foreignkey')
    op.drop_constraint('panel_payment_methods_ibfk_2', 'panel_payment_methods', type_='foreignkey')
    op.create_foreign_key(None, 'panel_payment_methods', 'payment_methods_currencies', ['currency_id'], ['id'], source_schema='panels', referent_schema='panels', onupdate='NO ACTION', ondelete='NO ACTION')
    op.create_foreign_key(None, 'panel_payment_methods', 'panels', ['panel_id'], ['id'], source_schema='panels', referent_schema='panels', onupdate='NO ACTION', ondelete='NO ACTION')
    op.create_foreign_key(None, 'panel_payment_methods', 'payment_methods', ['method_id'], ['id'], source_schema='panels', referent_schema='panels', onupdate='NO ACTION', ondelete='NO ACTION')
    op.drop_constraint('panel_payment_methods_bonuses_ibfk_1', 'panel_payment_methods_bonuses', type_='foreignkey')
    op.create_foreign_key(None, 'panel_payment_methods_bonuses', 'panel_payment_methods', ['panel_payment_methods_id'], ['id'], source_schema='panels', referent_schema='panels', onupdate='NO ACTION', ondelete='NO ACTION')
    op.drop_constraint('panel_payment_methods_options_ibfk_1', 'panel_payment_methods_options', type_='foreignkey')
    op.create_foreign_key(None, 'panel_payment_methods_options', 'panel_payment_methods', ['panel_payment_methods_id'], ['id'], source_schema='panels', referent_schema='panels', onupdate='NO ACTION', ondelete='NO ACTION')
    op.add_column('panels', sa.Column('timezone', sa.Integer(), nullable=False))
    op.drop_constraint('payment_methods_currencies_ibfk_1', 'payment_methods_currencies', type_='foreignkey')
    op.create_foreign_key(None, 'payment_methods_currencies', 'payment_methods', ['method_id'], ['id'], source_schema='panels', referent_schema='panels', onupdate='NO ACTION', ondelete='NO ACTION')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'payment_methods_currencies', schema='panels', type_='foreignkey')
    op.create_foreign_key('payment_methods_currencies_ibfk_1', 'payment_methods_currencies', 'payment_methods', ['method_id'], ['id'])
    op.drop_column('panels', 'timezone')
    op.drop_constraint(None, 'panel_payment_methods_options', schema='panels', type_='foreignkey')
    op.create_foreign_key('panel_payment_methods_options_ibfk_1', 'panel_payment_methods_options', 'panel_payment_methods', ['panel_payment_methods_id'], ['id'])
    op.drop_constraint(None, 'panel_payment_methods_bonuses', schema='panels', type_='foreignkey')
    op.create_foreign_key('panel_payment_methods_bonuses_ibfk_1', 'panel_payment_methods_bonuses', 'panel_payment_methods', ['panel_payment_methods_id'], ['id'])
    op.drop_constraint(None, 'panel_payment_methods', schema='panels', type_='foreignkey')
    op.drop_constraint(None, 'panel_payment_methods', schema='panels', type_='foreignkey')
    op.drop_constraint(None, 'panel_payment_methods', schema='panels', type_='foreignkey')
    op.create_foreign_key('panel_payment_methods_ibfk_2', 'panel_payment_methods', 'payment_methods', ['method_id'], ['id'])
    op.create_foreign_key('panel_payment_methods_ibfk_3', 'panel_payment_methods', 'panels', ['panel_id'], ['id'])
    op.create_foreign_key('panel_payment_methods_ibfk_1', 'panel_payment_methods', 'payment_methods_currencies', ['currency_id'], ['id'])
    op.drop_constraint(None, 'panel_options', schema='panels', type_='foreignkey')
    op.create_foreign_key('panel_options_ibfk_1', 'panel_options', 'panels', ['panel_id'], ['id'])
    op.drop_constraint(None, 'panel_domains', schema='panels', type_='foreignkey')
    op.create_foreign_key('panel_domains_ibfk_1', 'panel_domains', 'panels', ['panel_id'], ['id'])
    op.drop_index(op.f('ix_panels_panel_domains_domain_type'), table_name='panel_domains', schema='panels')
    op.create_index('ix_panels_panel_domains_domain_type', 'panel_domains', ['domain_type'], unique=False)
    op.drop_index(op.f('ix_panels_panel_domains_domain'), table_name='panel_domains', schema='panels')
    op.create_index('ix_panels_panel_domains_domain', 'panel_domains', ['domain'], unique=False)
    op.drop_constraint(None, 'panel_admin', schema='panels', type_='foreignkey')
    op.drop_constraint(None, 'panel_admin', schema='panels', type_='foreignkey')
    op.create_foreign_key('panel_admin_ibfk_1', 'panel_admin', 'panel_admin_hash', ['panel_admin_hash_id'], ['id'])
    op.create_foreign_key('panel_admin_ibfk_2', 'panel_admin', 'panels', ['panel_id'], ['id'])
    op.drop_column('panel_admin', 'timezone')
    # ### end Alembic commands ###
