"""add panel_admin.lang_code
Revision ID: 965ed06d52d0
Revises: 38009431dd94
Create Date: 2023-08-25 10:37:05.720945
"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '965ed06d52d0'
down_revision: Union[str, None] = '38009431dd94'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('panel_admin', sa.Column('lang_code', sa.String(length=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('panel_admin', 'lang_code')
    # ### end Alembic commands ###
