"""delete all tables

Revision ID: 0db8fcebc879
Revises: c1d5529674ef
Create Date: 2023-08-21 10:53:24.719455

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '0db8fcebc879'
down_revision: Union[str, None] = 'c1d5529674ef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('panel_payment_methods_options')
    op.drop_table('panel_domains')
    op.drop_table('panel_user_custom_fields')
    op.drop_table('panel_admin')
    op.drop_table('plan_list')
    op.drop_table('panel_options')
    op.drop_table('panel_payment_methods_bonuses')
    op.drop_table('panel_payment_methods')
    op.drop_table('panel_admin_hash')
    op.drop_table('panels')
    op.drop_table('payment_methods_currencies')
    op.drop_table('payment_methods')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'panel_payment_methods_bonuses',
        sa.Column('panel_payment_methods_id', mysql.INTEGER(), autoincrement=False, nullable=True),
        sa.Column('amount_percent', mysql.INTEGER(), autoincrement=False, nullable=True),
        sa.Column('deposit_from', mysql.INTEGER(), autoincrement=False, nullable=True),
        sa.Column('is_available', mysql.INTEGER(), autoincrement=False, nullable=True),
        sa.Column('created_at', mysql.INTEGER(), autoincrement=False, nullable=True),
        sa.Column('updated_at', mysql.INTEGER(), autoincrement=False, nullable=True),
        sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
        sa.ForeignKeyConstraint(['panel_payment_methods_id'], ['panel_payment_methods.id'],
                                name='panel_payment_methods_bonuses_ibfk_1'),
        sa.PrimaryKeyConstraint('id'),
        mysql_collate='utf8mb4_0900_ai_ci',
        mysql_default_charset='utf8mb4',
        mysql_engine='InnoDB'
    )
    op.create_index('ix_panels_payment_methods_currencies_method_id', 'payment_methods_currencies',
                    ['method_id'], unique=False)
    op.create_index('ix_panels_payment_methods_currencies_currency', 'payment_methods_currencies',
                    ['currency'], unique=False)
    op.create_table(
        'panel_options',
        sa.Column('panel_id', mysql.INTEGER(), autoincrement=False, nullable=True),
        sa.Column('signup_page', mysql.INTEGER(), autoincrement=False, nullable=True),
        sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
        sa.ForeignKeyConstraint(['panel_id'], ['panels.id'], name='panel_options_ibfk_1'),
        sa.PrimaryKeyConstraint('id'),
        mysql_collate='utf8mb4_0900_ai_ci',
        mysql_default_charset='utf8mb4',
        mysql_engine='InnoDB'
    )
    op.create_index('ix_panels_panels_plan_id', 'panels', ['plan_id'], unique=False)
    op.create_index('ix_panels_panels_currency', 'panels', ['currency'], unique=False)
    op.create_table(
        'plan_list',
        sa.Column('name', mysql.VARCHAR(length=45), nullable=True),
        sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
        sa.PrimaryKeyConstraint('id'),
        mysql_collate='utf8mb4_0900_ai_ci',
        mysql_default_charset='utf8mb4',
        mysql_engine='InnoDB'
    )
    op.create_table(
        'panel_admin',
        sa.Column('panel_id', mysql.INTEGER(), autoincrement=False, nullable=True),
        sa.Column('panel_admin_hash_id', mysql.INTEGER(), autoincrement=False, nullable=True),
        sa.Column('email', mysql.VARCHAR(length=300), nullable=True),
        sa.Column('password', mysql.VARCHAR(length=300), nullable=True),
        sa.Column('password_salt', mysql.VARCHAR(length=300), nullable=True),
        sa.Column('authorization_at', mysql.INTEGER(), autoincrement=False, nullable=True),
        sa.Column('status', mysql.INTEGER(), autoincrement=False, nullable=True, comment='1 - Active, 2 - Suspended'),
        sa.Column('created_at', mysql.INTEGER(), autoincrement=False, nullable=True),
        sa.Column('updated_at', mysql.INTEGER(), autoincrement=False, nullable=True),
        sa.Column('dark_mode', mysql.INTEGER(), autoincrement=False, nullable=True, comment='0 - disabled, 1 - enabled'),
        sa.Column('rules', mysql.TEXT(charset='utf8mb4', collation='utf8mb4_general_ci'), nullable=True),
        sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
        sa.ForeignKeyConstraint(['panel_admin_hash_id'], ['panel_admin_hash.id'], name='panel_admin_ibfk_1'),
        sa.ForeignKeyConstraint(['panel_id'], ['panels.id'], name='panel_admin_ibfk_2'),
        sa.PrimaryKeyConstraint('id'),
        mysql_collate='utf8mb4_0900_ai_ci',
        mysql_default_charset='utf8mb4',
        mysql_engine='InnoDB'
    )
    op.create_index('ix_panels_panel_admin_panel_id', 'panel_admin', ['panel_id'], unique=False)
    op.create_table(
        'user_agent_list',
        sa.Column('user_agent_name', mysql.VARCHAR(length=300), nullable=True),
        sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
        sa.PrimaryKeyConstraint('id'),
        mysql_collate='utf8mb4_0900_ai_ci',
        mysql_default_charset='utf8mb4',
        mysql_engine='InnoDB'
    )
    op.create_table(
        'panel_user_custom_fields',
        sa.Column('variable_name', mysql.VARCHAR(length=100), nullable=True),
        sa.Column('translation_code', mysql.VARCHAR(length=50), nullable=True),
        sa.Column('rules', mysql.JSON(), nullable=True),
        sa.Column('position', mysql.INTEGER(), autoincrement=False, nullable=True),
        sa.Column('default', mysql.INTEGER(), autoincrement=False, nullable=True),
        sa.Column('created_at', mysql.INTEGER(), autoincrement=False, nullable=True),
        sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
        sa.PrimaryKeyConstraint('id'),
        mysql_collate='utf8mb4_0900_ai_ci',
        mysql_default_charset='utf8mb4',
        mysql_engine='InnoDB'
    )
    op.create_table(
        'payment_methods',
        sa.Column('name', mysql.VARCHAR(length=100), nullable=True),
        sa.Column('addfunds_form', mysql.JSON(), nullable=True),
        sa.Column('settings_form', mysql.JSON(), nullable=True),
        sa.Column('settings_form_description', mysql.VARCHAR(length=300), nullable=True),
        sa.Column('has_take_fee', mysql.INTEGER(), autoincrement=False, nullable=True),
        sa.Column('has_extra_fee', mysql.INTEGER(), autoincrement=False, nullable=True),
        sa.Column('created_at', mysql.INTEGER(), autoincrement=False, nullable=True),
        sa.Column('updated_at', mysql.INTEGER(), autoincrement=False, nullable=True),
        sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
        sa.PrimaryKeyConstraint('id'),
        mysql_collate='utf8mb4_0900_ai_ci',
        mysql_default_charset='utf8mb4',
        mysql_engine='InnoDB'
    )
    op.create_table(
        'panel_domains',
        sa.Column('panel_id', mysql.INTEGER(), autoincrement=False, nullable=True),
        sa.Column('domain', mysql.VARCHAR(length=300), nullable=True),
        sa.Column('domain_type', mysql.INTEGER(), autoincrement=False, nullable=True,
                  comment='Тип домена: 1 - основной, 2 - системный, 3 - дополнительный'),
        sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
        sa.ForeignKeyConstraint(['panel_id'], ['panels.id'], name='panel_domains_ibfk_1'),
        sa.PrimaryKeyConstraint('id'),
        mysql_collate='utf8mb4_0900_ai_ci',
        mysql_default_charset='utf8mb4',
        mysql_engine='InnoDB'
    )
    op.create_index('ix_panels_panel_domains_panel_id', 'panel_domains', ['panel_id'], unique=False)
    op.create_index('ix_panels_panel_domains_domain_type', 'panel_domains', ['domain_type'], unique=False)
    op.create_index('ix_panels_panel_domains_domain', 'panel_domains', ['domain'], unique=False)
    op.create_table(
        'panel_payment_methods_options',
        sa.Column('panel_payment_methods_id', mysql.INTEGER(), autoincrement=False, nullable=True),
        sa.Column('options', mysql.TEXT(), nullable=True),
        sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
        sa.ForeignKeyConstraint(['panel_payment_methods_id'], ['panel_payment_methods.id'],
                                name='panel_payment_methods_options_ibfk_1'),
        sa.PrimaryKeyConstraint('id'),
        mysql_collate='utf8mb4_0900_ai_ci',
        mysql_default_charset='utf8mb4',
        mysql_engine='InnoDB'
    )
    op.create_table(
        'panel_admin_hash',
        sa.Column('panel_admin_id', mysql.INTEGER(), autoincrement=False, nullable=False),
        sa.Column('hash', mysql.VARCHAR(length=128), nullable=True),
        sa.Column('rand_string', mysql.VARCHAR(length=128), nullable=True),
        sa.Column('ip', mysql.INTEGER(), autoincrement=False, nullable=True),
        sa.Column('remember', mysql.INTEGER(), autoincrement=False, nullable=True),
        sa.Column('super_user', mysql.INTEGER(), autoincrement=False, nullable=True),
        sa.Column('created_at', mysql.INTEGER(), autoincrement=False, nullable=True),
        sa.Column('updated_at', mysql.INTEGER(), autoincrement=False, nullable=True),
        sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
        sa.PrimaryKeyConstraint('id'),
        mysql_collate='utf8mb4_0900_ai_ci',
        mysql_default_charset='utf8mb4',
        mysql_engine='InnoDB'
    )
    op.create_index('ix_panels_panel_options_panel_id', 'panel_options', ['panel_id'], unique=False)
    op.create_table(
        'panels',
        sa.Column('domain', mysql.VARCHAR(length=1000), nullable=True),
        sa.Column('created_at', mysql.INTEGER(), autoincrement=False, nullable=True),
        sa.Column('expired_at', mysql.INTEGER(), autoincrement=False, nullable=True),
        sa.Column('currency', mysql.VARCHAR(length=3), nullable=False),
        sa.Column('plan_id', mysql.INTEGER(), autoincrement=False, nullable=False),
        sa.Column('db_name', mysql.VARCHAR(length=45), nullable=False),
        sa.Column('status', mysql.VARCHAR(length=45), nullable=True, comment='1 - Active, 2 - paused, 3 - deleted'),
        sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
        sa.PrimaryKeyConstraint('id'),
        mysql_collate='utf8mb4_0900_ai_ci',
        mysql_default_charset='utf8mb4',
        mysql_engine='InnoDB'
    )
    op.create_table(
        'payment_methods_currencies',
        sa.Column('method_id', mysql.INTEGER(), autoincrement=False, nullable=True),
        sa.Column('currency', mysql.VARCHAR(length=50), nullable=True),
        sa.Column('position', mysql.INTEGER(), autoincrement=False, nullable=True),
        sa.Column('settings_form', mysql.JSON(), nullable=True),
        sa.Column('settings_form_description', mysql.VARCHAR(length=300), nullable=True),
        sa.Column('is_available', mysql.INTEGER(), autoincrement=False, nullable=True),
        sa.Column('created_at', mysql.INTEGER(), autoincrement=False, nullable=True),
        sa.Column('updated_at', mysql.INTEGER(), autoincrement=False, nullable=True),
        sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
        sa.ForeignKeyConstraint(['method_id'], ['payment_methods.id'], name='payment_methods_currencies_ibfk_1'),
        sa.PrimaryKeyConstraint('id'),
        mysql_collate='utf8mb4_0900_ai_ci',
        mysql_default_charset='utf8mb4',
        mysql_engine='InnoDB'
    )
    op.create_index('ix_panels_panel_admin_hash_panel_admin_id', 'panel_admin_hash', ['panel_admin_id'], unique=False)
    op.create_index('ix_panels_panel_admin_hash_hash', 'panel_admin_hash', ['hash'], unique=False)
    op.create_table(
        'panel_payment_methods',
        sa.Column('panel_id', mysql.INTEGER(), autoincrement=False, nullable=True),
        sa.Column('method_id', mysql.INTEGER(), autoincrement=False, nullable=True),
        sa.Column('currency_id', mysql.INTEGER(), autoincrement=False, nullable=True),
        sa.Column('is_visible', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
        sa.Column('webhook_url', mysql.VARCHAR(length=500), nullable=True),
        sa.Column('is_test_mode', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
        sa.Column('min_amount', mysql.INTEGER(), autoincrement=False, nullable=True),
        sa.Column('max_amount', mysql.INTEGER(), autoincrement=False, nullable=True),
        sa.Column('is_deleted', mysql.INTEGER(), autoincrement=False, nullable=True),
        sa.Column('amount_currency', mysql.INTEGER(), autoincrement=False, nullable=True),
        sa.Column('has_available_for_new_user', mysql.INTEGER(), autoincrement=False, nullable=True),
        sa.Column('position', mysql.INTEGER(), autoincrement=False, nullable=True),
        sa.Column('has_extra_fee', mysql.INTEGER(), autoincrement=False, nullable=True),
        sa.Column('has_take_from_user', mysql.INTEGER(), autoincrement=False, nullable=True),
        sa.Column('created_at', mysql.INTEGER(), autoincrement=False, nullable=True),
        sa.Column('updated_at', mysql.INTEGER(), autoincrement=False, nullable=True),
        sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
        sa.ForeignKeyConstraint(['currency_id'], ['payment_methods_currencies.id'], name='panel_payment_methods_ibfk_1'),
        sa.ForeignKeyConstraint(['method_id'], ['payment_methods.id'], name='panel_payment_methods_ibfk_2'),
        sa.ForeignKeyConstraint(['panel_id'], ['panels.id'], name='panel_payment_methods_ibfk_3'),
        sa.PrimaryKeyConstraint('id'),
        mysql_collate='utf8mb4_0900_ai_ci',
        mysql_default_charset='utf8mb4',
        mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
