"""rename panel_admin_hash super_user and change type panel_admin lastip

Revision ID: e4f5f23ddc6b
Revises: 965ed06d52d0
Create Date: 2023-08-28 10:31:34.986939

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'e4f5f23ddc6b'
down_revision: Union[str, None] = '965ed06d52d0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('panel_admin', 'lastip')
    op.add_column('panel_admin', sa.Column('lastip', sa.Integer(), nullable=True))
    op.add_column('panel_admin_hash', sa.Column('super_admin', sa.Integer(), nullable=True))
    op.drop_column('panel_admin_hash', 'super_user')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('panel_admin_hash', sa.Column('super_user', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('panel_admin_hash', 'super_admin')
    op.drop_column('panel_admin', 'lastip')
    op.add_column('panel_admin', sa.Column('lastip', sa.String(length=15), nullable=True))
    # ### end Alembic commands ###
