"""add_panels_languages

Revision ID: 1a6dee8ead45
Revises: c501b8c24276
Create Date: 2023-09-01 10:55:33.085020

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1a6dee8ead45'
down_revision: Union[str, None] = 'c501b8c24276'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('panel_language_messages',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('lang_code', sa.String(length=2), nullable=False),
    sa.Column('section', sa.String(length=50), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('value', sa.Text(length=500), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='panels',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_panels_panel_language_messages_code'), 'panel_language_messages', ['code'], unique=False, schema='panels')
    op.create_index(op.f('ix_panels_panel_language_messages_lang_code'), 'panel_language_messages', ['lang_code'], unique=False, schema='panels')
    op.create_index(op.f('ix_panels_panel_language_messages_section'), 'panel_language_messages', ['section'], unique=False, schema='panels')
    op.create_table('panel_languages',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=2), nullable=False),
    sa.Column('name', sa.String(length=30), nullable=False),
    sa.Column('direction', sa.Enum('ltr', 'rtl'), nullable=False, comment='ltr - Left to Right, rtl - Right to Left'),
    sa.Column('default', sa.Integer(), nullable=True, comment='0 - No, 1 - Yes'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code'),
    sa.UniqueConstraint('name'),
    schema='panels',
    mysql_engine='InnoDB'
    )
    op.drop_constraint('panel_admin_ibfk_2', 'panel_admin', type_='foreignkey')
    op.create_foreign_key(None, 'panel_admin', 'panels', ['panel_id'], ['id'], source_schema='panels', referent_schema='panels', onupdate='NO ACTION', ondelete='NO ACTION')
    op.drop_constraint('panel_admin_auth_codes_ibfk_2', 'panel_admin_auth_codes', type_='foreignkey')
    op.drop_constraint('panel_admin_auth_codes_ibfk_1', 'panel_admin_auth_codes', type_='foreignkey')
    op.create_foreign_key(None, 'panel_admin_auth_codes', 'panel_admin', ['panel_admin_id'], ['id'], source_schema='panels', referent_schema='panels', onupdate='NO ACTION', ondelete='NO ACTION')
    op.create_foreign_key(None, 'panel_admin_auth_codes', 'panel_admin_hash', ['panel_admin_hash_id'], ['id'], source_schema='panels', referent_schema='panels', onupdate='NO ACTION', ondelete='NO ACTION')
    op.create_index(op.f('ix_panels_panel_domains_domain'), 'panel_domains', ['domain'], unique=True, schema='panels')
    op.create_index(op.f('ix_panels_panel_domains_domain_type'), 'panel_domains', ['domain_type'], unique=False, schema='panels')
    op.drop_constraint('panel_domains_ibfk_1', 'panel_domains', type_='foreignkey')
    op.create_foreign_key(None, 'panel_domains', 'panels', ['panel_id'], ['id'], source_schema='panels', referent_schema='panels', onupdate='NO ACTION', ondelete='NO ACTION')
    op.drop_constraint('panel_options_ibfk_1', 'panel_options', type_='foreignkey')
    op.create_foreign_key(None, 'panel_options', 'panels', ['panel_id'], ['id'], source_schema='panels', referent_schema='panels', onupdate='NO ACTION', ondelete='NO ACTION')
    op.drop_constraint('panel_payment_methods_ibfk_3', 'panel_payment_methods', type_='foreignkey')
    op.drop_constraint('panel_payment_methods_ibfk_1', 'panel_payment_methods', type_='foreignkey')
    op.drop_constraint('panel_payment_methods_ibfk_2', 'panel_payment_methods', type_='foreignkey')
    op.create_foreign_key(None, 'panel_payment_methods', 'payment_methods', ['method_id'], ['id'], source_schema='panels', referent_schema='panels', onupdate='NO ACTION', ondelete='NO ACTION')
    op.create_foreign_key(None, 'panel_payment_methods', 'payment_methods_currencies', ['currency_id'], ['id'], source_schema='panels', referent_schema='panels', onupdate='NO ACTION', ondelete='NO ACTION')
    op.create_foreign_key(None, 'panel_payment_methods', 'panels', ['panel_id'], ['id'], source_schema='panels', referent_schema='panels', onupdate='NO ACTION', ondelete='NO ACTION')
    op.drop_constraint('panel_payment_methods_bonuses_ibfk_1', 'panel_payment_methods_bonuses', type_='foreignkey')
    op.create_foreign_key(None, 'panel_payment_methods_bonuses', 'panel_payment_methods', ['panel_payment_methods_id'], ['id'], source_schema='panels', referent_schema='panels', onupdate='NO ACTION', ondelete='NO ACTION')
    op.drop_constraint('panel_payment_methods_options_ibfk_1', 'panel_payment_methods_options', type_='foreignkey')
    op.create_foreign_key(None, 'panel_payment_methods_options', 'panel_payment_methods', ['panel_payment_methods_id'], ['id'], source_schema='panels', referent_schema='panels', onupdate='NO ACTION', ondelete='NO ACTION')
    op.drop_constraint('payment_methods_currencies_ibfk_1', 'payment_methods_currencies', type_='foreignkey')
    op.create_foreign_key(None, 'payment_methods_currencies', 'payment_methods', ['method_id'], ['id'], source_schema='panels', referent_schema='panels', onupdate='NO ACTION', ondelete='NO ACTION')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'payment_methods_currencies', schema='panels', type_='foreignkey')
    op.create_foreign_key('payment_methods_currencies_ibfk_1', 'payment_methods_currencies', 'payment_methods', ['method_id'], ['id'])
    op.drop_constraint(None, 'panel_payment_methods_options', schema='panels', type_='foreignkey')
    op.create_foreign_key('panel_payment_methods_options_ibfk_1', 'panel_payment_methods_options', 'panel_payment_methods', ['panel_payment_methods_id'], ['id'])
    op.drop_constraint(None, 'panel_payment_methods_bonuses', schema='panels', type_='foreignkey')
    op.create_foreign_key('panel_payment_methods_bonuses_ibfk_1', 'panel_payment_methods_bonuses', 'panel_payment_methods', ['panel_payment_methods_id'], ['id'])
    op.drop_constraint(None, 'panel_payment_methods', schema='panels', type_='foreignkey')
    op.drop_constraint(None, 'panel_payment_methods', schema='panels', type_='foreignkey')
    op.drop_constraint(None, 'panel_payment_methods', schema='panels', type_='foreignkey')
    op.create_foreign_key('panel_payment_methods_ibfk_2', 'panel_payment_methods', 'payment_methods', ['method_id'], ['id'])
    op.create_foreign_key('panel_payment_methods_ibfk_1', 'panel_payment_methods', 'payment_methods_currencies', ['currency_id'], ['id'])
    op.create_foreign_key('panel_payment_methods_ibfk_3', 'panel_payment_methods', 'panels', ['panel_id'], ['id'])
    op.drop_constraint(None, 'panel_options', schema='panels', type_='foreignkey')
    op.create_foreign_key('panel_options_ibfk_1', 'panel_options', 'panels', ['panel_id'], ['id'])
    op.drop_constraint(None, 'panel_domains', schema='panels', type_='foreignkey')
    op.create_foreign_key('panel_domains_ibfk_1', 'panel_domains', 'panels', ['panel_id'], ['id'])
    op.drop_index(op.f('ix_panels_panel_domains_domain_type'), table_name='panel_domains', schema='panels')
    op.drop_index(op.f('ix_panels_panel_domains_domain'), table_name='panel_domains', schema='panels')
    op.drop_constraint(None, 'panel_admin_auth_codes', schema='panels', type_='foreignkey')
    op.drop_constraint(None, 'panel_admin_auth_codes', schema='panels', type_='foreignkey')
    op.create_foreign_key('panel_admin_auth_codes_ibfk_1', 'panel_admin_auth_codes', 'panel_admin_hash', ['panel_admin_hash_id'], ['id'])
    op.create_foreign_key('panel_admin_auth_codes_ibfk_2', 'panel_admin_auth_codes', 'panel_admin', ['panel_admin_id'], ['id'])
    op.drop_constraint(None, 'panel_admin', schema='panels', type_='foreignkey')
    op.create_foreign_key('panel_admin_ibfk_2', 'panel_admin', 'panels', ['panel_id'], ['id'])
    op.drop_table('panel_languages', schema='panels')
    op.drop_index(op.f('ix_panels_panel_language_messages_section'), table_name='panel_language_messages', schema='panels')
    op.drop_index(op.f('ix_panels_panel_language_messages_lang_code'), table_name='panel_language_messages', schema='panels')
    op.drop_index(op.f('ix_panels_panel_language_messages_code'), table_name='panel_language_messages', schema='panels')
    op.drop_table('panel_language_messages', schema='panels')
    # ### end Alembic commands ###
