"""change type ip

Revision ID: 29395c63c6c9
Revises: e4f5f23ddc6b
Create Date: 2023-08-28 16:54:19.227996

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '29395c63c6c9'
down_revision: Union[str, None] = 'e4f5f23ddc6b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('panel_admin', 'lastip')
    op.drop_column('panel_admin_hash', 'ip')
    op.add_column('panel_admin', sa.Column('lastip', sa.String(length=39), nullable=True))
    op.add_column('panel_admin_hash', sa.Column('ip', sa.String(length=39), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('panel_admin_hash', 'ip')
    op.drop_column('panel_admin', 'lastip')
    op.add_column('panel_admin', sa.Column('lastip', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('panel_admin_hash', sa.Column('ip', mysql.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
