"""create panel_admin_auth_codes

Revision ID: 38009431dd94
Revises: cc5ea8669413
Create Date: 2023-08-24 09:25:37.126098

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '38009431dd94'
down_revision: Union[str, None] = 'cc5ea8669413'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'panel_admin_auth_codes',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('panel_admin_id', sa.Integer(), nullable=True),
        sa.Column('panel_admin_hash_id', sa.Integer(), nullable=True),
        sa.Column('auth_code', sa.Integer(), nullable=True),
        sa.Column('attempts', sa.Integer(), nullable=True),
        sa.Column('created_at', sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(['panel_admin_hash_id'], ['panels.panel_admin_hash.id'], onupdate='NO ACTION',
                                ondelete='NO ACTION'),
        sa.ForeignKeyConstraint(['panel_admin_id'], ['panels.panel_admin.id'], onupdate='NO ACTION',
                                ondelete='NO ACTION'),
        sa.PrimaryKeyConstraint('id'),
        schema='panels',
        mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_panels_panel_admin_auth_codes_panel_admin_hash_id'), 'panel_admin_auth_codes',
                    ['panel_admin_hash_id'], unique=False, schema='panels')
    op.create_index(op.f('ix_panels_panel_admin_auth_codes_panel_admin_id'), 'panel_admin_auth_codes',
                    ['panel_admin_id'], unique=False, schema='panels')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('panel_admin_auth_codes', schema='panels')
    # ### end Alembic commands ###
