"""panel_template_db: update panel_template(add tables)

Revision ID: 4b6e2f73ca2d
Revises: 06b255c9cef8
Create Date: 2023-08-16 12:23:10.289656

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '4b6e2f73ca2d'
down_revision: Union[str, None] = '06b255c9cef8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'user_custom_fields',
        sa.Column('user_id', sa.Integer(), nullable=True),
        sa.Column('default_field_id', sa.Integer(), nullable=True),
        sa.Column('position', sa.Integer(), nullable=True),
        sa.Column('rules', sa.JSON(), nullable=True),
        sa.Column('created_at', sa.Integer(), nullable=True),
        sa.Column('updated_at', sa.Integer(), nullable=True),
        sa.Column('id', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(['user_id'], ['panel_template.users.id'], onupdate='NO ACTION', ondelete='NO ACTION'),
        sa.PrimaryKeyConstraint('id'),
        schema='panel_template',
        mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_panel_template_user_custom_fields_user_id'), 'user_custom_fields',
                    ['user_id'], unique=False, schema='panel_template')
    op.create_table(
        'user_details',
        sa.Column('user_id', sa.Integer(), nullable=True),
        sa.Column('field_name', sa.String(length=300), nullable=True),
        sa.Column('field_value', sa.String(length=300), nullable=True),
        sa.Column('id', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(['user_id'], ['panel_template.users.id'], onupdate='NO ACTION', ondelete='NO ACTION'),
        sa.PrimaryKeyConstraint('id'),
        schema='panel_template',
        mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_panel_template_user_details_user_id'), 'user_details',
                    ['user_id'], unique=False, schema='panel_template')
    op.create_table(
        'payment_methods_translations',
        sa.Column('panel_payment_methods_id', sa.Integer(), nullable=True),
        sa.Column('lang_code', sa.String(length=5), nullable=True),
        sa.Column('name', sa.String(length=50), nullable=True),
        sa.Column('descriptions', sa.String(length=200), nullable=True),
        sa.Column('created_at', sa.Integer(), nullable=True),
        sa.Column('updated_at', sa.Integer(), nullable=True),
        sa.Column('id', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(['panel_payment_methods_id'], ['panels.panel_payment_methods.id'], onupdate='NO ACTION',
                                ondelete='NO ACTION'),
        sa.PrimaryKeyConstraint('id'),
        schema='panel_template',
        mysql_engine='InnoDB'
    )
    op.create_table(
        'user_payment_methods',
        sa.Column('user_id', sa.Integer(), nullable=True),
        sa.Column('panel_payment_method_id', sa.Integer(), nullable=True),
        sa.Column('is_enabled', sa.Boolean(), nullable=True),
        sa.Column('id', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(['panel_payment_method_id'], ['panels.panel_payment_methods.id'], onupdate='NO ACTION',
                                ondelete='NO ACTION'),
        sa.ForeignKeyConstraint(['user_id'], ['panel_template.users.id'], onupdate='NO ACTION', ondelete='NO ACTION'),
        sa.PrimaryKeyConstraint('id'),
        schema='panel_template',
        mysql_engine='InnoDB'
    )
    op.drop_table('users_custom_fields')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'users_custom_fields',
        sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=True),
        sa.Column('field_name', mysql.VARCHAR(length=300), nullable=True),
        sa.Column('field_value', mysql.VARCHAR(length=300), nullable=True),
        sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='users_custom_fields_ibfk_1'),
        sa.PrimaryKeyConstraint('id'),
        mysql_collate='utf8mb4_0900_ai_ci',
        mysql_default_charset='utf8mb4',
        mysql_engine='InnoDB'
    )
    op.create_index('ix_panel_template_users_custom_fields_user_id', 'users_custom_fields', ['user_id'], unique=False)
    op.drop_table('user_payment_methods', schema='panel_template')
    op.drop_table('payment_methods_translations', schema='panel_template')
    op.drop_table('user_details', schema='panel_template')
    op.drop_table('user_custom_fields', schema='panel_template')
    # ### end Alembic commands ###
