"""change type ip

Revision ID: 15fcd0d95bc0
Revises: d33d5cfac3d4
Create Date: 2023-08-28 16:59:57.460025

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '15fcd0d95bc0'
down_revision: Union[str, None] = 'd33d5cfac3d4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('activity_log', 'ip')
    op.drop_column('users', 'auth_ip')
    op.drop_column('users_activity_log', 'ip')
    op.add_column('activity_log', sa.Column('ip', sa.String(length=39), nullable=True))
    op.add_column('users', sa.Column('auth_ip', sa.String(length=39), nullable=True))
    op.add_column('users_activity_log', sa.Column('ip', sa.String(length=39), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users_activity_log', 'ip')
    op.drop_column('users', 'auth_ip')
    op.drop_column('activity_log', 'ip')
    op.add_column('users_activity_log', sa.Column('ip', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('auth_ip', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('activity_log', sa.Column('ip', mysql.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
