"""delete all tables

Revision ID: e3602c3b234e
Revises: 4b6e2f73ca2d
Create Date: 2023-08-21 10:55:16.713125

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'e3602c3b234e'
down_revision: Union[str, None] = '4b6e2f73ca2d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_details')
    op.drop_table('users_custom_rates')
    op.drop_table('user_custom_fields')
    op.drop_table('users_password_history')
    op.drop_table('users_activity_log')
    op.drop_table('users_auth_codes')
    op.drop_table('user_payment_methods')
    op.drop_table('activity_log_details')
    op.drop_table('users_apikey_history')
    op.drop_table('payment_methods_translations')
    op.drop_table('activity_log')
    op.drop_table('user_agent_list')
    op.drop_table('users')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'user_agent_list',
        sa.Column('user_agent_name', mysql.VARCHAR(length=300), nullable=True),
        sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
        sa.PrimaryKeyConstraint('id'),
        mysql_collate='utf8mb4_0900_ai_ci',
        mysql_default_charset='utf8mb4',
        mysql_engine='InnoDB'
    )
    op.create_table(
        'activity_log',
        sa.Column('panel_admin_id', mysql.INTEGER(), autoincrement=False, nullable=True),
        sa.Column('user_agent_id', mysql.INTEGER(), autoincrement=False, nullable=True),
        sa.Column('super_admin', mysql.INTEGER(), autoincrement=False, nullable=True),
        sa.Column('created_at', mysql.INTEGER(), autoincrement=False, nullable=True),
        sa.Column('ip', mysql.INTEGER(), autoincrement=False, nullable=True),
        sa.Column('details_id', mysql.INTEGER(), autoincrement=False, nullable=True),
        sa.Column('url', mysql.VARCHAR(length=1000), nullable=True),
        sa.Column('event_id', mysql.INTEGER(), autoincrement=False, nullable=True),
        sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
        sa.ForeignKeyConstraint(['panel_admin_id'], ['panels.panel_admin.id'], name='activity_log_ibfk_1'),
        sa.ForeignKeyConstraint(['user_agent_id'], ['user_agent_list.id'], name='activity_log_ibfk_2'),
        sa.PrimaryKeyConstraint('id'),
        mysql_collate='utf8mb4_0900_ai_ci',
        mysql_default_charset='utf8mb4',
        mysql_engine='InnoDB'
    )
    op.create_index('ix_panel_template_activity_log_user_agent_id', 'activity_log', ['user_agent_id'], unique=False)
    op.create_index('ix_panel_template_activity_log_panel_admin_id', 'activity_log', ['panel_admin_id'], unique=False)
    op.create_table(
        'payment_methods_translations',
        sa.Column('panel_payment_methods_id', mysql.INTEGER(), autoincrement=False, nullable=True),
        sa.Column('lang_code', mysql.VARCHAR(length=5), nullable=True),
        sa.Column('name', mysql.VARCHAR(length=50), nullable=True),
        sa.Column('descriptions', mysql.VARCHAR(length=200), nullable=True),
        sa.Column('created_at', mysql.INTEGER(), autoincrement=False, nullable=True),
        sa.Column('updated_at', mysql.INTEGER(), autoincrement=False, nullable=True),
        sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
        sa.ForeignKeyConstraint(['panel_payment_methods_id'], ['panels.panel_payment_methods.id'],
                                name='payment_methods_translations_ibfk_1'),
        sa.PrimaryKeyConstraint('id'),
        mysql_collate='utf8mb4_0900_ai_ci',
        mysql_default_charset='utf8mb4',
        mysql_engine='InnoDB'
    )
    op.create_table(
        'users_apikey_history',
        sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=True),
        sa.Column('apikey', mysql.VARCHAR(length=128), nullable=True),
        sa.Column('created_at', mysql.INTEGER(), autoincrement=False, nullable=True),
        sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='users_apikey_history_ibfk_1'),
        sa.PrimaryKeyConstraint('id'),
        mysql_collate='utf8mb4_0900_ai_ci',
        mysql_default_charset='utf8mb4',
        mysql_engine='InnoDB'
    )
    op.create_index('ix_panel_template_users_apikey_history_user_id', 'users_apikey_history', ['user_id'], unique=False)
    op.create_table(
        'activity_log_details',
        sa.Column('request_data', mysql.TEXT(), nullable=True),
        sa.Column('activity_log_details_id', mysql.INTEGER(), autoincrement=False, nullable=True),
        sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
        sa.ForeignKeyConstraint(['activity_log_details_id'], ['activity_log.id'], name='activity_log_details_ibfk_1'),
        sa.PrimaryKeyConstraint('id'),
        mysql_collate='utf8mb4_0900_ai_ci',
        mysql_default_charset='utf8mb4',
        mysql_engine='InnoDB'
    )
    op.create_table(
        'user_payment_methods',
        sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=True),
        sa.Column('panel_payment_method_id', mysql.INTEGER(), autoincrement=False, nullable=True),
        sa.Column('is_enabled', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
        sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
        sa.ForeignKeyConstraint(['panel_payment_method_id'], ['panels.panel_payment_methods.id'],
                                name='user_payment_methods_ibfk_1'),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='user_payment_methods_ibfk_2'),
        sa.PrimaryKeyConstraint('id'),
        mysql_collate='utf8mb4_0900_ai_ci',
        mysql_default_charset='utf8mb4',
        mysql_engine='InnoDB'
    )
    op.create_table(
        'users_auth_codes',
        sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=True),
        sa.Column('event', mysql.VARCHAR(length=45), nullable=True),
        sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='users_auth_codes_ibfk_1'),
        sa.PrimaryKeyConstraint('id'),
        mysql_collate='utf8mb4_0900_ai_ci',
        mysql_default_charset='utf8mb4',
        mysql_engine='InnoDB'
    )
    op.create_index('ix_panel_template_users_auth_codes_user_id', 'users_auth_codes', ['user_id'], unique=False)
    op.create_table(
        'users_activity_log',
        sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=True),
        sa.Column('user_agent_id', mysql.INTEGER(), autoincrement=False, nullable=True),
        sa.Column('ip', mysql.INTEGER(), autoincrement=False, nullable=True),
        sa.Column('event', mysql.INTEGER(), autoincrement=False, nullable=True),
        sa.Column('location', mysql.VARCHAR(length=1000), nullable=True),
        sa.Column('created_at', mysql.INTEGER(), autoincrement=False, nullable=True),
        sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
        sa.ForeignKeyConstraint(['user_agent_id'], ['user_agent_list.id'], name='users_activity_log_ibfk_1'),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='users_activity_log_ibfk_2'),
        sa.PrimaryKeyConstraint('id'),
        mysql_collate='utf8mb4_0900_ai_ci',
        mysql_default_charset='utf8mb4',
        mysql_engine='InnoDB'
    )
    op.create_index('ix_panel_template_users_activity_log_user_id', 'users_activity_log',
                    ['user_id'], unique=False)
    op.create_index('ix_panel_template_users_activity_log_user_agent_id', 'users_activity_log',
                    ['user_agent_id'], unique=False)
    op.create_table(
        'users',
        sa.Column('username', mysql.VARCHAR(length=300), nullable=True),
        sa.Column('email', mysql.VARCHAR(length=300), nullable=True),
        sa.Column('refferer_id', mysql.INTEGER(), autoincrement=False, nullable=True),
        sa.Column('password', mysql.VARCHAR(length=300), nullable=True),
        sa.Column('password_salt', mysql.VARCHAR(length=300), nullable=True),
        sa.Column('password_method', mysql.INTEGER(), autoincrement=False, nullable=True),
        sa.Column('balance', mysql.FLOAT(), nullable=True),
        sa.Column('spent', mysql.FLOAT(), nullable=True),
        sa.Column('created_at', mysql.INTEGER(), autoincrement=False, nullable=True),
        sa.Column('updated_at', mysql.INTEGER(), autoincrement=False, nullable=True),
        sa.Column('auth_at', mysql.INTEGER(), autoincrement=False, nullable=True),
        sa.Column('auth_ip', mysql.INTEGER(), autoincrement=False, nullable=True),
        sa.Column('apikey', mysql.VARCHAR(length=64), nullable=True),
        sa.Column('refferal_key', mysql.VARCHAR(length=8), nullable=True),
        sa.Column('discount', mysql.INTEGER(), autoincrement=False, nullable=True),
        sa.Column('timezone', mysql.INTEGER(), autoincrement=False, nullable=True),
        sa.Column('terms_confirm', mysql.INTEGER(), autoincrement=False, nullable=True),
        sa.Column('lang_code', mysql.VARCHAR(length=3), nullable=True),
        sa.Column('email_status', mysql.INTEGER(), autoincrement=False, nullable=True,
                  comment='0 - not confirmed, 1 - confirmed'),
        sa.Column('status', mysql.INTEGER(), autoincrement=False, nullable=True,
                  comment='1 - active, 2 - suspended'),
        sa.Column('options', mysql.TEXT(), nullable=True),
        sa.Column('currency', mysql.VARCHAR(length=4), nullable=True),
        sa.Column('has_subscription', mysql.INTEGER(), autoincrement=False, nullable=True),
        sa.Column('has_drip_feed', mysql.INTEGER(), autoincrement=False, nullable=True),
        sa.Column('has_ticket', mysql.INTEGER(), autoincrement=False, nullable=True),
        sa.Column('has_refill_task', mysql.INTEGER(), autoincrement=False, nullable=True),
        sa.Column('custom_rates_quantity', mysql.INTEGER(), autoincrement=False, nullable=True),
        sa.Column('confirmed', mysql.INTEGER(), autoincrement=False, nullable=True),
        sa.Column('cpf_field', mysql.VARCHAR(length=200), nullable=True),
        sa.Column('two_fa_enabled', mysql.INTEGER(), autoincrement=False, nullable=True),
        sa.Column('two_fa_generated_at', mysql.INTEGER(), autoincrement=False, nullable=True),
        sa.Column('two_fa_generate_blocked', mysql.INTEGER(), autoincrement=False, nullable=True),
        sa.Column('resend_email_at', mysql.INTEGER(), autoincrement=False, nullable=True),
        sa.Column('change_email_at', mysql.INTEGER(), autoincrement=False, nullable=True),
        sa.Column('orders_count', mysql.INTEGER(), autoincrement=False, nullable=True),
        sa.Column('apikey_updated_at', mysql.INTEGER(), autoincrement=False, nullable=True),
        sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
        sa.PrimaryKeyConstraint('id'),
        mysql_collate='utf8mb4_0900_ai_ci',
        mysql_default_charset='utf8mb4',
        mysql_engine='InnoDB'
    )
    op.create_index('refferal_key', 'users', ['refferal_key'], unique=False)
    op.create_index('ix_panel_template_users_username', 'users', ['username'], unique=False)
    op.create_table(
        'users_password_history',
        sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=True),
        sa.Column('password', mysql.VARCHAR(length=300), nullable=True),
        sa.Column('password_salt', mysql.VARCHAR(length=300), nullable=True),
        sa.Column('created_at', mysql.INTEGER(), autoincrement=False, nullable=True),
        sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='users_password_history_ibfk_1'),
        sa.PrimaryKeyConstraint('id'),
        mysql_collate='utf8mb4_0900_ai_ci',
        mysql_default_charset='utf8mb4',
        mysql_engine='InnoDB'
    )
    op.create_index('ix_panel_template_users_password_history_user_id', 'users_password_history',
                    ['user_id'], unique=False)
    op.create_table(
        'user_custom_fields',
        sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=True),
        sa.Column('default_field_id', mysql.INTEGER(), autoincrement=False, nullable=True),
        sa.Column('position', mysql.INTEGER(), autoincrement=False, nullable=True),
        sa.Column('rules', mysql.JSON(), nullable=True),
        sa.Column('created_at', mysql.INTEGER(), autoincrement=False, nullable=True),
        sa.Column('updated_at', mysql.INTEGER(), autoincrement=False, nullable=True),
        sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='user_custom_fields_ibfk_1'),
        sa.PrimaryKeyConstraint('id'),
        mysql_collate='utf8mb4_0900_ai_ci',
        mysql_default_charset='utf8mb4',
        mysql_engine='InnoDB'
    )
    op.create_index('ix_panel_template_user_custom_fields_user_id', 'user_custom_fields', ['user_id'], unique=False)
    op.create_table(
        'users_custom_rates',
        sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=True),
        sa.Column('service_id', mysql.INTEGER(), autoincrement=False, nullable=True),
        sa.Column('rate', mysql.DECIMAL(precision=21, scale=0), nullable=True),
        sa.Column('is_percent', mysql.INTEGER(), autoincrement=False, nullable=True,
                  comment='0 - fixed service rate, 1 - percent  of service rate'),
        sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='users_custom_rates_ibfk_1'),
        sa.PrimaryKeyConstraint('id'),
        mysql_collate='utf8mb4_0900_ai_ci',
        mysql_default_charset='utf8mb4',
        mysql_engine='InnoDB'
    )
    op.create_index('ix_panel_template_users_custom_rates_user_id', 'users_custom_rates',
                    ['user_id'], unique=False)
    op.create_index('ix_panel_template_users_custom_rates_service_id', 'users_custom_rates',
                    ['service_id'], unique=False)
    op.create_table(
        'user_details',
        sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=True),
        sa.Column('field_name', mysql.VARCHAR(length=300), nullable=True),
        sa.Column('field_value', mysql.VARCHAR(length=300), nullable=True),
        sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='user_details_ibfk_1'),
        sa.PrimaryKeyConstraint('id'),
        mysql_collate='utf8mb4_0900_ai_ci',
        mysql_default_charset='utf8mb4',
        mysql_engine='InnoDB'
    )
    op.create_index('ix_panel_template_user_details_user_id', 'user_details', ['user_id'], unique=False)
    # ### end Alembic commands ###
