"""delete admin_auth_codes

Revision ID: d33d5cfac3d4
Revises: f74a9c290eef
Create Date: 2023-08-24 09:27:22.317567

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'd33d5cfac3d4'
down_revision: Union[str, None] = 'f74a9c290eef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('admin_auth_codes')
    op.drop_table('admin_auth_codes', schema='panel_first_domain')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'admin_auth_codes',
        sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
        sa.Column('panel_admin_id', mysql.INTEGER(), autoincrement=False, nullable=True),
        sa.Column('panel_admin_hash_id', mysql.INTEGER(), autoincrement=False, nullable=True),
        sa.Column('auth_code', mysql.INTEGER(), autoincrement=False, nullable=True),
        sa.Column('attempts', mysql.INTEGER(), autoincrement=False, nullable=True),
        sa.Column('created_at', mysql.INTEGER(), autoincrement=False, nullable=True),
        sa.ForeignKeyConstraint(['panel_admin_hash_id'], ['panels.panel_admin_hash.id'], name='admin_auth_codes_ibfk_1'),
        sa.ForeignKeyConstraint(['panel_admin_id'], ['panels.panel_admin.id'], name='admin_auth_codes_ibfk_2'),
        sa.PrimaryKeyConstraint('id'),
        schema='panel_first_domain',
        mysql_collate='utf8mb4_0900_ai_ci',
        mysql_default_charset='utf8mb4',
        mysql_engine='InnoDB'
    )
    op.create_index('ix_panel_first_domain_admin_auth_codes_panel_admin_id', 'admin_auth_codes',
                    ['panel_admin_id'], unique=False, schema='panel_first_domain')
    op.create_index('ix_panel_first_domain_admin_auth_codes_panel_admin_hash_id', 'admin_auth_codes',
                    ['panel_admin_hash_id'], unique=False, schema='panel_first_domain')
    op.create_table(
        'admin_auth_codes',
        sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
        sa.Column('panel_admin_id', mysql.INTEGER(), autoincrement=False, nullable=True),
        sa.Column('panel_admin_hash_id', mysql.INTEGER(), autoincrement=False, nullable=True),
        sa.Column('auth_code', mysql.INTEGER(), autoincrement=False, nullable=True),
        sa.Column('attempts', mysql.INTEGER(), autoincrement=False, nullable=True),
        sa.Column('created_at', mysql.INTEGER(), autoincrement=False, nullable=True),
        sa.ForeignKeyConstraint(['panel_admin_hash_id'], ['panels.panel_admin_hash.id'], name='admin_auth_codes_ibfk_1'),
        sa.ForeignKeyConstraint(['panel_admin_id'], ['panels.panel_admin.id'], name='admin_auth_codes_ibfk_2'),
        sa.PrimaryKeyConstraint('id'),
        mysql_collate='utf8mb4_0900_ai_ci',
        mysql_default_charset='utf8mb4',
        mysql_engine='InnoDB'
    )
    op.create_index('ix_admin_auth_codes_panel_admin_id', 'admin_auth_codes', ['panel_admin_id'], unique=False)
    op.create_index('ix_admin_auth_codes_panel_admin_hash_id', 'admin_auth_codes',
                    ['panel_admin_hash_id'], unique=False)
    # ### end Alembic commands ###
